-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-24 14:50:14 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

--4.      Написати PL/SQL код, що створює таблиці та ключі згідно 
--логічної моделі. Створити необхідні CONSTRAINTS. 
--Результат роботи зберегти у файлі create.sql

CREATE TABLE museum (
    museum_name  VARCHAR2(256) NOT NULL,
    museum_type  VARCHAR2(256) NOT NULL,
    m_state      VARCHAR2(128) NOT NULL,
    city         VARCHAR2(4000) NOT NULL
);

ALTER TABLE museum ADD CONSTRAINT museum_pk PRIMARY KEY ( museum_name );

CREATE TABLE museum_city (
    city VARCHAR2(4000) NOT NULL
);

ALTER TABLE museum_city ADD CONSTRAINT museum_city_pk PRIMARY KEY ( city );

CREATE TABLE museum_income (
    museum_name  VARCHAR2(256) NOT NULL,
    income_date       INTEGER NOT NULL,
    income       INTEGER
);

ALTER TABLE museum_income ADD CONSTRAINT museum_income_pk PRIMARY KEY ( income_date,
                                                                        museum_name );

CREATE TABLE museum_location (
    m_state  VARCHAR2(126) NOT NULL,
    city     VARCHAR2(4000) NOT NULL
);

ALTER TABLE museum_location ADD CONSTRAINT museum_location_pk PRIMARY KEY ( city,
                                                                            m_state );

CREATE TABLE museum_state (
    m_state VARCHAR2(126) NOT NULL
);

ALTER TABLE museum_state ADD CONSTRAINT museum_state_pk PRIMARY KEY ( m_state );

CREATE TABLE museum_type (
    museum_type VARCHAR2(256) NOT NULL
);

ALTER TABLE museum_type ADD CONSTRAINT museum_type_pk PRIMARY KEY ( museum_type );

CREATE TABLE visit (
    visitor_name  VARCHAR2(256) NOT NULL,
    ticket_price  INTEGER,
    museum_name   VARCHAR2(256) NOT NULL
);

ALTER TABLE visit ADD CONSTRAINT visit_pk PRIMARY KEY ( visitor_name,
                                                        museum_name );

CREATE TABLE visitor (
    name VARCHAR2(256) NOT NULL
);

ALTER TABLE visitor ADD CONSTRAINT visitor_pk PRIMARY KEY ( name );

ALTER TABLE museum_income
    ADD CONSTRAINT museum_income_fk FOREIGN KEY ( museum_name )
        REFERENCES museum ( museum_name );

ALTER TABLE museum_location
    ADD CONSTRAINT museum_location_city_fk FOREIGN KEY ( city )
        REFERENCES museum_city ( city );

ALTER TABLE museum
    ADD CONSTRAINT museum_location_fk FOREIGN KEY ( city,
                                                    m_state )
        REFERENCES museum_location ( city,
                                     m_state );

ALTER TABLE museum_location
    ADD CONSTRAINT museum_location_state_fk FOREIGN KEY ( m_state )
        REFERENCES museum_state ( m_state );

ALTER TABLE museum
    ADD CONSTRAINT museum_type_fk FOREIGN KEY ( museum_type )
        REFERENCES museum_type ( museum_type );

ALTER TABLE visit
    ADD CONSTRAINT visit_museum_fk FOREIGN KEY ( museum_name )
        REFERENCES museum ( museum_name );

ALTER TABLE visit
    ADD CONSTRAINT visit_visitor_fk FOREIGN KEY ( visitor_name )
        REFERENCES visitor ( name );


ALTER TABLE visitor RENAME COLUMN name TO visitor_name;

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
